auth_enabled: false

server:
  http_listen_port: 3100

common:
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    instance_addr: 127.0.0.1
    kvstore:
      store: inmemory

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h
    - from: "2024-11-01"
      index:
        period: 24h
        prefix: loki_ops_index_
      object_store: filesystem
      schema: v13
      store: tsdb

limits_config:
  # TODO: remove after schema change
  # https://grafana.com/docs/loki/latest/setup/upgrade/
  allow_structured_metadata: false

ruler:
  alertmanager_url: http://localhost:9093
