# docs:
# https://prometheus.io/docs/alerting/latest/configuration/
#
# based on:
# https://github.com/prometheus/alertmanager/blob/main/doc/examples/simple.yml
global:
  smtp_smarthost: 'mailhog:25'
  smtp_from: 'alertmanager@example.org'

# The directory from which notification templates are read.
templates:
  - '/etc/alertmanager/template/*.tmpl'

# The root route on which each incoming alert enters.
route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: mails
  routes:
    - matchers:
        - service=~"foo1|foo2|baz"
      receiver: mails

receivers:
  - name: 'mails'
    email_configs:
      - to: 'alerts@example.org'
