FROM prom/blackbox-exporter:v0.19.0
# https://hub.docker.com/r/prom/blackbox-exporter/tags
# https://github.com/prometheus/blackbox_exporter/blob/v0.17.0/Dockerfile

COPY blackbox.yml /config/blackbox.yml
