# https://grafana.com/docs/grafana/latest/administration/provisioning/
apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:
- name: Prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://prometheus.prom.0-main.de
  isDefault: true
  version: 1
  editable: true
