{
 "title": "containers",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "project",
    "query": {
     "query": "label_values(container_label_com_docker_compose_project)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "scrape errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "container_scrape_error" }
   ]
  },
  {
   "title": "CPU units",
   "type": "timeseries",
   "description": "Use the values as guidance for CPU limits, e.g.\nhttps://docs.docker.com/compose/compose-file/compose-file-v3/#resources",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (name) (rate(container_cpu_user_seconds_total{image!=\"\", container_label_com_docker_compose_project=~\"$project\"}[$__rate_interval]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "mem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (name) (container_memory_usage_bytes{image!=\"\", container_label_com_docker_compose_project=~\"$project\"})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "count",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(container_last_seen{image!=\"\"})"
    }
   ]
  },
  {
   "title": "mem (MB)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{image!=\"\"})/1024/1024"
    }
   ]
  },
  {
   "title": "Network Received",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (name) (irate(container_network_receive_bytes_total{image!=\"\", container_label_com_docker_compose_project=~\"$project\"}[5m]))",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Network Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(container_network_transmit_bytes_total{image!=\"\", container_label_com_docker_compose_project=~\"$project\"}[5m])",
     "legendFormat": "{{name}} rx"
    }
   ]
  },
  {
   "title": "CPU (%)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_user_seconds_total{image!=\"\"}[5m]) * 100)"
    }
   ]
  },
  {
   "title": "FS reads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 2, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(container_fs_reads_bytes_total{image!=\"\", container_label_com_docker_compose_project=~\"$project\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "FS writes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "irate(container_fs_writes_bytes_total{image!=\"\", container_label_com_docker_compose_project=~\"$project\"}[5m])",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}